# GS CV Test 1

Explorando _Grid Search_ e _Cross Validation_ para melhoramento de Hiperparâmetros de classificador **Perceptron* para o conjunto de dados iris

## Importando bibliotecas

In [1]:
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import cross_validate, GridSearchCV, KFold, train_test_split

In [2]:
# Carregando dataset
X, y = load_iris(return_X_y=True)

# Instanciando Scaler
sc = StandardScaler().fit(X)

# Pré-processando dados
X_train_trans = sc.transform(X)

## K-Fold

a função `split` retorna um array de índices, com 5 splits divide o conjunto de treino em 5 _folders_, uma com índices para teste e os demais índices para treino, os dados de treino como parâmetro ajudam a balancear a divisão, caso seja necessário

In [3]:
for train, test in KFold(n_splits=5).split(X_train_trans, y):
    print(test)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

In [4]:
cv_result = cross_validate(
    estimator=Perceptron(),
    X=X_train_trans,
    y=y,
    cv=5
)
mean = cv_result['test_score'].mean()
std = cv_result['test_score'].std()
print(f'mean = {mean}; std = {std}')
cv_result

mean = 0.8866666666666667; std = 0.07180219742846003

{'fit_time': array([0.00869203, 0.00821161, 0.00384617, 0.00357223, 0.0058713 ]),
 'score_time': array([0.02299237, 0.00066113, 0.00049305, 0.00053287, 0.00054836]),
 'test_score': array([0.8       , 0.96666667, 0.93333333, 0.8       , 0.93333333])}

## Grid Search Cross Validation

In [5]:
gscv = GridSearchCV(
    estimator=Perceptron(),
    param_grid={
        'max_iter':[1, 10, 30, 50, 100, 500, 1000],
        'eta0':[0.01, 0.1, 0.5, 1, 2],
    },
    cv=5
).fit(X_train_trans, y)

gscv.best_params_, gscv.best_score_

({'eta0': 0.1, 'max_iter': 10}, 0.9199999999999999)

In [6]:
gridDF = pd.DataFrame(gscv.cv_results_)
gridDF

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_eta0,param_max_iter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006101,0.001943,0.000751,0.000131,0.01,1,"{'eta0': 0.01, 'max_iter': 1}",0.766667,0.700000,0.733333,0.833333,0.933333,0.793333,0.082731,31
1,0.005703,0.000502,0.000724,0.000166,0.01,10,"{'eta0': 0.01, 'max_iter': 10}",0.833333,0.966667,0.866667,0.900000,0.966667,0.906667,0.053333,2
2,0.005800,0.001466,0.000783,0.000168,0.01,30,"{'eta0': 0.01, 'max_iter': 30}",0.833333,0.966667,0.866667,0.900000,0.933333,0.900000,0.047140,3
3,0.005735,0.001654,0.000730,0.000218,0.01,50,"{'eta0': 0.01, 'max_iter': 50}",0.833333,0.966667,0.866667,0.900000,0.933333,0.900000,0.047140,3
4,0.005440,0.001729,0.000776,0.000450,0.01,100,"{'eta0': 0.01, 'max_iter': 100}",0.833333,0.966667,0.866667,0.900000,0.933333,0.900000,0.047140,3
5,0.003166,0.000210,0.000429,0.000032,0.01,500,"{'eta0': 0.01, 'max_iter': 500}",0.833333,0.966667,0.866667,0.900000,0.933333,0.900000,0.047140,3
6,0.002997,0.000108,0.000443,0.000056,0.01,1000,"{'eta0': 0.01, 'max_iter': 1000}",0.833333,0.966667,0.866667,0.900000,0.933333,0.900000,0.047140,3
7,0.002869,0.000046,0.000454,0.000077,0.1,1,"{'eta0': 0.1, 'max_iter': 1}",0.766667,0.700000,0.733333,0.833333,0.933333,0.793333,0.082731,31
8,0.003099,0.000267,0.000413,0.000024,0.1,10,"{'eta0': 0.1, 'max_iter': 10}",0.866667,0.966667,0.933333,0.866667,0.966667,0.920000,0.045216,1
9,0.003030,0.000153,0.000421,0.000012,0.1,30,"{'eta0': 0.1, 'max_iter': 30}",0.800000,0.966667,0.933333,0.866667,0.933333,0.900000,0.059628,3
10,0.003207,0.000253,0.000489,0.000097,0.1,50,"{'eta0': 0.1, 'max_iter': 50}",0.800000,0.966667,0.933333,0.866667,0.933333,0.900000,0.059628,3
11,0.004293,0.001839,0.000737,0.000611,0.1,100,"{'eta0': 0.1, 'max_iter': 100}",0.800000,0.966667,0.933333,0.866667,0.933333,0.900000,0.059628,3
12,0.003098,0.000175,0.000411,0.000014,0.1,500,"{'eta0': 0.1, 'max_iter': 500}",0.800000,0.966667,0.933333,0.866667,0.933333,0.900000,0.059628,3
13,0.003863,0.000984,0.000479,0.000082,0.1,1000,"{'eta0': 0.1, 'max_iter': 1000}",0.800000,0.966667,0.933333,0.866667,0.933333,0.900000,0.059628,3
14,0.003303,0.000427,0.000465,0.000056,0.5,1,"{'eta0': 0.5, 'max_iter': 1}",0.766667,0.700000,0.733333,0.833333,0.933333,0.793333,0.082731,31
15,0.003782,0.000772,0.000474,0.000067,0.5,10,"{'eta0': 0.5, 'max_iter': 10}",0.866667,0.966667,0.933333,0.733333,0.966667,0.893333,0.087939,13
16,0.003885,0.000784,0.000443,0.000040,0.5,30,"{'eta0': 0.5, 'max_iter': 30}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
17,0.005148,0.002043,0.000654,0.000201,0.5,50,"{'eta0': 0.5, 'max_iter': 50}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
18,0.007828,0.002131,0.001602,0.000890,0.5,100,"{'eta0': 0.5, 'max_iter': 100}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
19,0.008864,0.000780,0.001320,0.000421,0.5,500,"{'eta0': 0.5, 'max_iter': 500}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
20,0.007834,0.001913,0.001060,0.000352,0.5,1000,"{'eta0': 0.5, 'max_iter': 1000}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
21,0.007086,0.002425,0.000787,0.000311,1,1,"{'eta0': 1, 'max_iter': 1}",0.766667,0.700000,0.733333,0.833333,0.933333,0.793333,0.082731,31
22,0.003911,0.001195,0.000781,0.000660,1,10,"{'eta0': 1, 'max_iter': 10}",0.866667,0.966667,0.933333,0.733333,0.966667,0.893333,0.087939,13
23,0.003442,0.000655,0.000424,0.000019,1,30,"{'eta0': 1, 'max_iter': 30}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
24,0.003666,0.000587,0.000906,0.000675,1,50,"{'eta0': 1, 'max_iter': 50}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
25,0.003122,0.000132,0.000418,0.000012,1,100,"{'eta0': 1, 'max_iter': 100}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
26,0.003726,0.000785,0.000482,0.000119,1,500,"{'eta0': 1, 'max_iter': 500}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
27,0.003294,0.000435,0.000416,0.000014,1,1000,"{'eta0': 1, 'max_iter': 1000}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
28,0.003182,0.000524,0.000523,0.000226,2,1,"{'eta0': 2, 'max_iter': 1}",0.766667,0.700000,0.733333,0.833333,0.933333,0.793333,0.082731,31
29,0.003345,0.000533,0.000436,0.000028,2,10,"{'eta0': 2, 'max_iter': 10}",0.866667,0.966667,0.933333,0.733333,0.966667,0.893333,0.087939,13
30,0.003442,0.000712,0.000478,0.000119,2,30,"{'eta0': 2, 'max_iter': 30}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
31,0.003817,0.000952,0.000648,0.000237,2,50,"{'eta0': 2, 'max_iter': 50}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
32,0.003842,0.000966,0.000500,0.000128,2,100,"{'eta0': 2, 'max_iter': 100}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
33,0.003783,0.000737,0.000792,0.000526,2,500,"{'eta0': 2, 'max_iter': 500}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16
34,0.004747,0.002072,0.000667,0.000211,2,1000,"{'eta0': 2, 'max_iter': 1000}",0.800000,0.966667,0.933333,0.800000,0.933333,0.886667,0.071802,16

In [7]:
gridDF[['params', 'mean_test_score', 'std_test_score', 'rank_test_score']]

,params,mean_test_score,std_test_score,rank_test_score
0,"{'eta0': 0.01, 'max_iter': 1}",0.793333,0.082731,31
1,"{'eta0': 0.01, 'max_iter': 10}",0.906667,0.053333,2
2,"{'eta0': 0.01, 'max_iter': 30}",0.900000,0.047140,3
3,"{'eta0': 0.01, 'max_iter': 50}",0.900000,0.047140,3
4,"{'eta0': 0.01, 'max_iter': 100}",0.900000,0.047140,3
5,"{'eta0': 0.01, 'max_iter': 500}",0.900000,0.047140,3
6,"{'eta0': 0.01, 'max_iter': 1000}",0.900000,0.047140,3
7,"{'eta0': 0.1, 'max_iter': 1}",0.793333,0.082731,31
8,"{'eta0': 0.1, 'max_iter': 10}",0.920000,0.045216,1
9,"{'eta0': 0.1, 'max_iter': 30}",0.900000,0.059628,3
10,"{'eta0': 0.1, 'max_iter': 50}",0.900000,0.059628,3
11,"{'eta0': 0.1, 'max_iter': 100}",0.900000,0.059628,3
12,"{'eta0': 0.1, 'max_iter': 500}",0.900000,0.059628,3
13,"{'eta0': 0.1, 'max_iter': 1000}",0.900000,0.059628,3
14,"{'eta0': 0.5, 'max_iter': 1}",0.793333,0.082731,31
15,"{'eta0': 0.5, 'max_iter': 10}",0.893333,0.087939,13
16,"{'eta0': 0.5, 'max_iter': 30}",0.886667,0.071802,16
17,"{'eta0': 0.5, 'max_iter': 50}",0.886667,0.071802,16
18,"{'eta0': 0.5, 'max_iter': 100}",0.886667,0.071802,16
19,"{'eta0': 0.5, 'max_iter': 500}",0.886667,0.071802,16
20,"{'eta0': 0.5, 'max_iter': 1000}",0.886667,0.071802,16
21,"{'eta0': 1, 'max_iter': 1}",0.793333,0.082731,31
22,"{'eta0': 1, 'max_iter': 10}",0.893333,0.087939,13
23,"{'eta0': 1, 'max_iter': 30}",0.886667,0.071802,16
24,"{'eta0': 1, 'max_iter': 50}",0.886667,0.071802,16
25,"{'eta0': 1, 'max_iter': 100}",0.886667,0.071802,16
26,"{'eta0': 1, 'max_iter': 500}",0.886667,0.071802,16
27,"{'eta0': 1, 'max_iter': 1000}",0.886667,0.071802,16
28,"{'eta0': 2, 'max_iter': 1}",0.793333,0.082731,31
29,"{'eta0': 2, 'max_iter': 10}",0.893333,0.087939,13
30,"{'eta0': 2, 'max_iter': 30}",0.886667,0.071802,16
31,"{'eta0': 2, 'max_iter': 50}",0.886667,0.071802,16
32,"{'eta0': 2, 'max_iter': 100}",0.886667,0.071802,16
33,"{'eta0': 2, 'max_iter': 500}",0.886667,0.071802,16
34,"{'eta0': 2, 'max_iter': 1000}",0.886667,0.071802,16

In [8]:
gridDF[['params', 'mean_test_score', 'std_test_score', 'rank_test_score']].sort_values(by='rank_test_score')

,params,mean_test_score,std_test_score,rank_test_score
8,"{'eta0': 0.1, 'max_iter': 10}",0.920000,0.045216,1
1,"{'eta0': 0.01, 'max_iter': 10}",0.906667,0.053333,2
11,"{'eta0': 0.1, 'max_iter': 100}",0.900000,0.059628,3
2,"{'eta0': 0.01, 'max_iter': 30}",0.900000,0.047140,3
3,"{'eta0': 0.01, 'max_iter': 50}",0.900000,0.047140,3
4,"{'eta0': 0.01, 'max_iter': 100}",0.900000,0.047140,3
5,"{'eta0': 0.01, 'max_iter': 500}",0.900000,0.047140,3
6,"{'eta0': 0.01, 'max_iter': 1000}",0.900000,0.047140,3
9,"{'eta0': 0.1, 'max_iter': 30}",0.900000,0.059628,3
10,"{'eta0': 0.1, 'max_iter': 50}",0.900000,0.059628,3
12,"{'eta0': 0.1, 'max_iter': 500}",0.900000,0.059628,3
13,"{'eta0': 0.1, 'max_iter': 1000}",0.900000,0.059628,3
29,"{'eta0': 2, 'max_iter': 10}",0.893333,0.087939,13
15,"{'eta0': 0.5, 'max_iter': 10}",0.893333,0.087939,13
22,"{'eta0': 1, 'max_iter': 10}",0.893333,0.087939,13
24,"{'eta0': 1, 'max_iter': 50}",0.886667,0.071802,16
30,"{'eta0': 2, 'max_iter': 30}",0.886667,0.071802,16
32,"{'eta0': 2, 'max_iter': 100}",0.886667,0.071802,16
27,"{'eta0': 1, 'max_iter': 1000}",0.886667,0.071802,16
26,"{'eta0': 1, 'max_iter': 500}",0.886667,0.071802,16
25,"{'eta0': 1, 'max_iter': 100}",0.886667,0.071802,16
31,"{'eta0': 2, 'max_iter': 50}",0.886667,0.071802,16
17,"{'eta0': 0.5, 'max_iter': 50}",0.886667,0.071802,16
34,"{'eta0': 2, 'max_iter': 1000}",0.886667,0.071802,16
20,"{'eta0': 0.5, 'max_iter': 1000}",0.886667,0.071802,16
19,"{'eta0': 0.5, 'max_iter': 500}",0.886667,0.071802,16
18,"{'eta0': 0.5, 'max_iter': 100}",0.886667,0.071802,16
33,"{'eta0': 2, 'max_iter': 500}",0.886667,0.071802,16
16,"{'eta0': 0.5, 'max_iter': 30}",0.886667,0.071802,16
23,"{'eta0': 1, 'max_iter': 30}",0.886667,0.071802,16
21,"{'eta0': 1, 'max_iter': 1}",0.793333,0.082731,31
28,"{'eta0': 2, 'max_iter': 1}",0.793333,0.082731,31
14,"{'eta0': 0.5, 'max_iter': 1}",0.793333,0.082731,31
7,"{'eta0': 0.1, 'max_iter': 1}",0.793333,0.082731,31
0,"{'eta0': 0.01, 'max_iter': 1}",0.793333,0.082731,31

![Data Distribution](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)